name: Mirror to Team Repository

on:
  push:
    branches: [ main, develop ]
  schedule:
    # Run every hour to ensure sync
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Add team repository as remote
      run: |
        git remote add team https://${{ secrets.TEAM_GITHUB_TOKEN }}@github.com/pitcrewlabs/pcl-app.git

    - name: Push to team repository
      run: |
        git push team main
        git push team --all
        git push team --tags
      env:
        TEAM_GITHUB_TOKEN: ${{ secrets.TEAM_GITHUB_TOKEN }}
